/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        TJ2560HRCEXT_CATEGORY: 'MUGEN',
        TJ2560HRCEXT_PLAYSOUND: 'on board buzzer play sound with frequency %1 Hz for %2 second',
        TJ2560HRCEXT_PLAYTONEFORBEAT: 'on board buzzer play tone %1 for %2 beat',
        TJ2560HRCEXT_SETTEMPO: 'set on board buzzer tempo to (bpm) %1',
        TJ2560HRCEXT_PLAYRINGTONE: 'on board buzzer play ringtone %1',
        TJ2560HRCEXT_CONNECTION: 'connection',
        TJ2560HRCEXT_DISCONNECTION: 'disconnet',
        TJ2560HRCEXT_DIDI: 'button pushed',
        TJ2560HRCEXT_MODE1: 'mode1',
        TJ2560HRCEXT_MODE2: 'mode2',
        TJ2560HRCEXT_MODE3: 'mode3',
        TJ2560HRCEXT_SURPRISE: 'surprise',
        TJ2560HRCEXT_OHOOH: 'OhOoh',
        TJ2560HRCEXT_OHOOH2: 'OhOoh2',
        TJ2560HRCEXT_CUDDLY: 'cuddly',
        TJ2560HRCEXT_SLEEPING: 'sleeping',
        TJ2560HRCEXT_HAPPY: 'happy',
        TJ2560HRCEXT_SUPERHAPPY: 'super happy',
        TJ2560HRCEXT_HAPPYSHORT: 'happy short',
        TJ2560HRCEXT_SAD: 'sad',
        TJ2560HRCEXT_CONFUSED: 'confused',
        TJ2560HRCEXT_FART1: 'fart1',
        TJ2560HRCEXT_FART2: 'fart2',
        TJ2560HRCEXT_FART3: 'fart3',
        TJ2560HRCEXT_ONBOARDDRIVERRUN: 'on board motor driver %1 run %2 speed %3',
        TJ2560HRCEXT_ONBOARDDRIVERSTOP: 'on board motor driver %1 stop',
        TJ2560HRCEXT_FORWARD: 'counter-clockwise',
        TJ2560HRCEXT_BACK: 'clockwise',
        TJ2560HRCEXT_ONBOARDENCODERREAD: 'read on board encoder %1 value',
        TJ2560HRCEXT_ONBOARDENCODERRESET: 'reset on board encoder %1 value',
        TJ2560HRCEXT_BLUETOOTHPRINT: 'bluetooth send %1 %2',
        TJ2560HRCEXT_WARP: 'warp',
        TJ2560HRCEXT_NOWARP: 'no-warp',
        TJ2560HRCEXT_BLUETOOTHAVAILABLE: 'bluetooth available data length',
        TJ2560HRCEXT_BLUETOOTHREADABYTE: 'bluetooth read a byte',
        TJ2560HRCEXT_IRRECIVE: 'read ir remoter data',
        TJ2560HRCEXT_ISIRPRESS: 'ir remoter channel %1 key %1 is press?',
        TJ2560HRCEXT_POWER: 'power',
        TJ2560HRCEXT_SETSERVO: 'set %1 servo angle %2',
        TJ2560HRCEXT_SETTIME: 'delay %1 us'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        TJ2560HRCEXT_CATEGORY: '板载功能',
        TJ2560HRCEXT_PLAYSOUND: '板载蜂鸣器以频率 %1 Hz 播放声音持续 %2 秒',
        TJ2560HRCEXT_PLAYTONEFORBEAT: '板载蜂鸣器播放音调 %1 持续 %2 节拍',
        TJ2560HRCEXT_SETTEMPO: '设置板载蜂鸣器节奏为 (bpm) %1',
        TJ2560HRCEXT_PLAYRINGTONE: '板载蜂鸣器播放铃声 %1',
        TJ2560HRCEXT_CONNECTION: '连接',
        TJ2560HRCEXT_DISCONNECTION: '断开',
        TJ2560HRCEXT_DIDI: '按键按下',
        TJ2560HRCEXT_MODE1: '模式1',
        TJ2560HRCEXT_MODE2: '模式2',
        TJ2560HRCEXT_MODE3: '模式3',
        TJ2560HRCEXT_SURPRISE: '惊讶',
        TJ2560HRCEXT_OHOOH: '哦哦',
        TJ2560HRCEXT_OHOOH2: '哦哦2',
        TJ2560HRCEXT_CUDDLY: '可爱',
        TJ2560HRCEXT_SLEEPING: '正在睡觉',
        TJ2560HRCEXT_HAPPY: '开心',
        TJ2560HRCEXT_SUPERHAPPY: '非常开心',
        TJ2560HRCEXT_HAPPYSHORT: '开心短',
        TJ2560HRCEXT_SAD: '难过',
        TJ2560HRCEXT_CONFUSED: '困惑',
        TJ2560HRCEXT_FART1: '放屁1',
        TJ2560HRCEXT_FART2: '放屁2',
        TJ2560HRCEXT_FART3: '放屁3',
        TJ2560HRCEXT_ONBOARDDRIVERRUN: '驱动 %1 板载电机 %2 方向以速度 %3 旋转',
        TJ2560HRCEXT_ONBOARDDRIVERSTOP: '驱动板载电机 %1 停止旋转',
        TJ2560HRCEXT_FORWARD: '逆时针',
        TJ2560HRCEXT_BACK: '顺时针',
        TJ2560HRCEXT_ONBOARDENCODERREAD: '读取板载编码器 %1 数值',
        TJ2560HRCEXT_ONBOARDENCODERRESET: '重置板载编码器 %1 数值',
        TJ2560HRCEXT_BLUETOOTHPRINT: '蓝牙模块发送 %1 %2',
        TJ2560HRCEXT_WARP: '换行',
        TJ2560HRCEXT_NOWARP: '不换行',
        TJ2560HRCEXT_BLUETOOTHAVAILABLE: '蓝牙模块可用数据长度',
        TJ2560HRCEXT_BLUETOOTHREADABYTE: '蓝牙模块读取一个字节',
        TJ2560HRCEXT_IRRECIVE: '读取红外遥控数据',
        TJ2560HRCEXT_ISIRPRESS: '红外遥控器通道 %1 按键 %2 被按下?',
        TJ2560HRCEXT_POWER: '电源',
        TJ2560HRCEXT_SETSERVO: '设置 %1 舵机端口 %2 角度 %3',
        TJ2560HRCEXT_SETTIME: '等待 %1 微秒',
        TJ2560HRCEXT_ONBOARDWATERPUMPON:'驱动 %1 板载水泵以速率 %2 运行',
        TJ2560HRCEXT_ONBOARDWATERPUMPOFF:'驱动板载水泵 %1 停止运行',
    });
    return Blockly;
}

exports = addMsg;
